# action.yml
name: "Publish Dart/Flutter package"
description: "Publish Dart/Flutter package"
inputs:
  credentials:
    description: "Credentials JSON to use"
    required: true
  path:
    description: '(Optional) Package directory (default: ".")'
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Publish
      shell: bash
      id: publish
      run: |
        set -e

        cat <<EOF > $PUB_CACHE/credentials.json
          ${{ inputs.credentials }}
          EOF

        pub publish
      working-directory: ${{ inputs.path }}
