# action.yml
name: "Publish Dart/Flutter package"
description: "Publish Dart/Flutter package"
inputs:
  credentials:
    description: "Credentials JSON to use"
    required: true
  path:
    description: '(Optional) Package directory (default: ".")'
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Publish
      shell: bash
      id: publish
      run: |
        set -e

        
        printf '${{ inputs.credentials }}' > ~/.config/dart/pub-credentials.json

        dart pub publish --force
      working-directory: ${{ inputs.path }}
